.TH ADJBACKLIGHT 1 ADJBACKLIGHT
.SH NAME
adjbacklight - Convenient method for adjusting the backlight on your portable computer
.SH SYNOPSIS
.B adjbacklight
[-g | -s
.RB [ + | - ]\fIlevel\fP[ % | %% ]]
[-a |
.IR device \ ...]
.SH DESCRIPTION
.B adjbacklight
can be used to fetch or set the backlight non-interactively.
If these feature is not used, it starts a interactive user
interface in the terminal.
.P
.B adjbacklight
installs with the set-uid bit set, to enable any user to
change the backlight on the computer.
.P
.B adjbacklight
was originally designed for small netbooks that are not running
.BR X .
However, it is still suitable for desktop computers and can
be used inside
.BR X .
In fact it seems to work for all machines with backlight, which
is not true for
.BR xbacklight (1).
.V adjbacklight
uses
.IR /sys/class/backlight .
.B adjbacklight
as been retrofitted to be convenient for use inside
.B X
on desktop computers, with commands that lets it be used
non-interactively with hotkeys set up in
.BR xbindkeys (1).
.SH OPTIONS
.TP
.BR \-a
Run for all devices, including ACPI devices.
.TP
.BR \-g
Get average brightness on devices.
.TP
.BR -s \ \fIlevel\fP
Set brightness on devices by actual value.
.TP
.BR -s\ + \fIlevel\fP
Increase brightness on devices by actual value.
.TP
.BR -s\ - \fIlevel\fP
Decrease brightness on devices by actual value.
.TP
.BR -s \ \fIlevel\fP%
Set brightness on devices by percentage-points.
.TP
.BR -s\ + \fIlevel\fP%
Increase brightness on devices by percentage-points.
.TP
.BR -s\ - \fIlevel\fP%
Decrease brightness on devices by percentage-points.
.TP
.BR -s \ \fIlevel\fP%%
Set brightness on devices by percentage.
.TP
.BR -s\ + \fIlevel\fP%%
Increase brightness on devices by percentage.
.TP
.BR -s\ - \fIlevel\fP%%
Decrease brightness on devices by percentage.
.SH KEYBOARD
.TP
.BR left ,\  down
Darken the screen.
.TP
.BR right ,\  up
Brighten the screen.
.TP
.BR q ,\  enter ,\  C-d
Continue to next controller, or if at last, quit.
.SH "SEE ALSO"
.BR xbindkeys (1),
.BR xbacklight (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
