#!/usr/bin/env bash

# adjbacklight – Convient method for adjusting the backlight on your portable computer
# 
# Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if (( $# > 0 )); then
    for arg in "$@"; do
	case "$arg" in
	    ("-c" | "--copyright" | "--copying")
		cat <<.


adjbacklight – Convient method for adjusting the backlight on your portable computer

Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


.
		exit 0
		;;
	    ("-w" | "--warranty")
		cat <<.


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.


.
		exit 0
		;;
	esac
    done
    cat <<.


adjbacklight – Convient method for adjusting the backlight on your portable computer

USAGE: adjbacklight [ -c | -w ]

Run with options to adjust the backlight on your screens.


OPTIONS:

-c
--copyright
--copying       Display copyright information

-w
--warranty      Display warranty disclaimer


KEYBOARD:

←
↓               Darken the screen

→
↑               Brighten the screen

q
enter
C-d             Continue to next controller, or if at last, quit



Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.
    exit 0
fi


cat <<.


If the program is abnormally aborted there may be effects
on the terminal, the following commands should reset it:

    stty icanon echo
    echo -en '\033[?25h'




.

stty -icanon -echo
if [[ $? = 0 ]]; then
    echo -en '\033[?25l'
    for dir in $(exec ls -1 --color=no "/sys/class/backlight/" | grep -v '^acpi_video'); do
	sudo java -cp ${BASH_SOURCE%/*} Adjbacklight `stty size` "$dir"
    done
    echo -en '\033[?25h'
    stty icanon echo
else
    echo -e '\e[1;31m::\e[39m Epic failure\e[21m'
fi
