#!/usr/bin/env bash

# adjbacklight – Convient method for adjusting the backlight on your portable computer
# 
# Copyright © 2012, 2013, 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


all=0
devices=()

if (( $# > 0 )); then
    for arg in "$@"; do
	case "$arg" in
	    ("-a" | "--all")
		all=1
		;;
	    ("-c" | "--copyright" | "--copying")
		cat <<.


adjbacklight – Convient method for adjusting the backlight on your portable computer

Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


.
		exit 0
		;;
	    ("-w" | "--warranty")
		cat <<.


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.


.
		exit 0
		;;
	    (*)
		if [ ! "${arg::1}" = "-" ]; then
		    devices+=( "$arg" )
		fi
		;;
	esac
    done
    if [ $all = 0 ] && [ ${#devices[@]} = 0 ]; then
	cat <<.


adjbacklight – Convient method for adjusting the backlight on your portable computer

USAGE: adjbacklight [ -c | -w | -a | DEVICE...]

Run with options to adjust the backlight on your monitors.


OPTIONS:

-c
--copyright
--copying       Display copyright information

-w
--warranty      Display warranty disclaimer

-a
--all           Run for all devices, including ACPI devices 


KEYBOARD:

←
↓               Darken the screen

→
↑               Brighten the screen

q
enter
C-d             Continue to next controller, or if at last, quit



Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.
	exit 0
    fi
fi


cat <<.


If the program is abnormally aborted there may be effects
on the terminal, the following commands should reset it:

    stty icanon echo
    echo -en '\e[?25h'




.

stty -icanon -echo
if [ $? = 0 ]; then
    echo -en '\e[?25l'
    if [ ! ${#devices[@]} = 0 ]; then
	for dir in "${devices[@]}"; do
	    if [ "${dir::21}" = "/sys/class/backlight/" ]; then
		dir="${dir:21}"
	    fi
	    sudo java -cp ${BASH_SOURCE%/*} Adjbacklight `stty size` "$dir"
	done
    elif [ $all = 0 ]; then
	for dir in $(exec ls -1 --color=no "/sys/class/backlight/" | grep -v '^acpi_video'); do
	    sudo java -cp ${BASH_SOURCE%/*} Adjbacklight `stty size` "$dir"
	done
    else
	for dir in $(exec ls -1 --color=no "/sys/class/backlight/"); do
	    sudo java -cp ${BASH_SOURCE%/*} Adjbacklight `stty size` "$dir"
	done
    fi
    echo -en '\e[?25h'
    stty icanon echo
else
    echo -e '\e[1;31m::\e[39m Epic failure\e[21m'
fi
